# Copied from https://github.com/rerun-io/rerun_template
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [ opened, synchronize ]

name: Rust

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  rust-check:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rust-docs, clippy, rustfmt
          toolchain: 1.85.1
          override: true

      - name: Install packages (Linux)
        if: runner.os == 'Linux' && false # TODO: enable if eframe is part of the project, otherwise remove
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          # some deps used by eframe, if that is part of the project
          packages: libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev # libgtk-3-dev is used by rfd
          version: 1.0
          execute_install_scripts: true

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.42.1

      - name: Rustfmt
        run: pixi run cargo fmt --all -- --check

      - name: check --all-features
        run: pixi run cargo check --all-features --all-targets

      - name: check default features
        run: pixi run cargo check --all-targets

      - name: check --no-default-features
        run: pixi run cargo check --no-default-features --all-targets

      - name: Test doc-tests
        run: pixi run cargo test --doc --all-features

      - name: cargo doc --lib
        run: pixi run cargo doc --lib --no-deps --all-features

      - name: cargo doc --document-private-items
        run: pixi run cargo doc --document-private-items --no-deps --all-features

      - name: Build tests
        run: pixi run cargo build --tests --all-features

      - name: Run test
        run: pixi run cargo test --all-features

      - name: Clippy
        run: pixi run cargo clippy --all-targets --all-features -- -D warnings

  # ---------------------------------------------------------------------------

  check_wasm:
    name: Check wasm32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.85.1
          override: true
          target: wasm32-unknown-unknown
          components: clippy,rustfmt

      - name: Check wasm32
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target wasm32-unknown-unknown --lib

      - name: Clippy wasm32
        env:
          CLIPPY_CONF_DIR: "scripts/clippy_wasm" # Use scripts/clippy_wasm/clippy.toml
        run: cargo clippy --target wasm32-unknown-unknown --lib -- -D warnings

  # ---------------------------------------------------------------------------

  cargo-deny:
    name: Check Rust dependencies (cargo-deny)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v2
      with:
        rust-version: "1.85.1"
        log-level: warn
        command: check
